from app.card import Card

cards = {
    'ace_of_spades': Card('AS'),
    'two_of_spades': Card('2S'),
    'three_of_spades': Card('3S'),
    'four_of_spades': Card('4S'),
    'five_of_spades': Card('5S'),
    'six_of_spades': Card('6S'),
    'seven_of_spades': Card('7S'),
    'eight_of_spades': Card('8S'),
    'nine_of_spades': Card('9S'),
    'ten_of_spades': Card('10S'),
    'jack_of_spades': Card('JS'),
    'queen_of_spades': Card('QS'),
    'king_of_spades': Card('KS'),

    'ace_of_hearts': Card('AH'),
    'two_of_hearts': Card('2H'),
    'three_of_hearts': Card('3H'),
    'four_of_hearts': Card('4H'),
    'five_of_hearts': Card('5H'),
    'six_of_hearts': Card('6H'),
    'seven_of_hearts': Card('7H'),
    'eight_of_hearts': Card('8H'),
    'nine_of_hearts': Card('9H'),
    'ten_of_hearts': Card('10H'),
    'jack_of_hearts': Card('JH'),
    'queen_of_hearts': Card('QH'),
    'king_of_hearts': Card('KH'),

    'ace_of_diamonds': Card('AD'),
    'two_of_diamonds': Card('2D'),
    'three_of_diamonds': Card('3D'),
    'four_of_diamonds': Card('4D'),
    'five_of_diamonds': Card('5D'),
    'six_of_diamonds': Card('6D'),
    'seven_of_diamonds': Card('7D'),
    'eight_of_diamonds': Card('8D'),
    'nine_of_diamonds': Card('9D'),
    'ten_of_diamonds': Card('10D'),
    'jack_of_diamonds': Card('JD'),
    'queen_of_diamonds': Card('QD'),
    'king_of_diamonds': Card('KD'),

    'ace_of_clubs': Card('AC'),
    'two_of_clubs': Card('2C'),
    'three_of_clubs': Card('3C'),
    'four_of_clubs': Card('4C'),
    'five_of_clubs': Card('5C'),
    'six_of_clubs': Card('6C'),
    'seven_of_clubs': Card('7C'),
    'eight_of_clubs': Card('8C'),
    'nine_of_clubs': Card('9C'),
    'ten_of_clubs': Card('10C'),
    'jack_of_clubs': Card('JC'),
    'queen_of_clubs': Card('QC'),
    'king_of_clubs': Card('KC'),
}
